// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "serviceURL": string;
      "targetLang": string;
      "radius": number;
      "autoPrefetch": boolean;
      "fontScale": string;
      "lineSpacing": string;
    };
  }
}
